apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-csv-api
spec:
  replicas: 1
  selector:
    matchLabels:
      name: node-csv-api
  template:
    metadata:
      labels:
        name: node-csv-api
    spec:
      containers:
        - name: node-csv-api
          image: pmoits/node-csv-api:latest
          ports:
            - containerPort: 8080
