apiVersion: v1
kind: Service
metadata:
  name: node-csv-api
  labels:
    name: node-csv-api
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    name: node-csv-api
